openapi: '3.0.2'
info:
  contact:
    email: kristof.krenn@smaxtec.com
  description: Get a quota online
  title: Quotation API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: Quote
paths:
  /rfqs:
    post:
      tags:
        - Quote
      description: Create a quoute
      operationId: createQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '200':
          description: OK

components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        product:
          type: string
          maxLength: 20
          pattern: '(\w+\W*)*'
        quantity:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000
        price:
          type: number
          minimum: 0
        shipment:
          type: string
          enum:
            - FOB
            - DAT
        mode:
          type: string
          pattern: "[A-Z]{3}"
          maxLength: 3

